"""Generate a complete, runnable PCSWMM/SWMM ``.inp`` for the Teton scenario.

Pulls the stage-storage curve out of ``tests/data/teton_minimal.inp``, routes a
Froehlich (2008) piping breach through it with swmm-breach, then writes a
self-contained ``.inp`` (``teton_pcswmm_example.inp``) that PCSWMM can open and
run directly: the breach hydrograph is applied as an ``[INFLOWS]`` time series
at the dam toe and routed down a trapezoidal channel to a free outfall.

All units are SI (CMS / meters) to match the metric Teton storage curve.

Run from the repo root with the project venv:

    .venv\\Scripts\\python.exe examples\\build_teton_pcswmm.py
"""

from datetime import datetime
from pathlib import Path

from swmm_breach import FailureMode, froehlich, simulate
from swmm_breach.swmm import load_storage_curve, format_inflows_block

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
SRC_INP = REPO / "tests" / "data" / "teton_minimal.inp"
OUT_INP = HERE / "teton_pcswmm_example.inp"

# Breach event clock (arbitrary; t=0 of the hydrograph maps here).
START = datetime(2026, 6, 5, 14, 0, 0)

# ---- 1. Pull the storage curve straight out of the fixture .inp ----------
sc, node = load_storage_curve(SRC_INP, "TetonRes")
crest = node.invert_elevation + node.max_depth      # 900 + 87 = 987 m

# ---- 2. Predict breach geometry and route it -----------------------------
geom = froehlich.predict(
    volume_m3=sc.volume_at(crest),
    height_m=node.max_depth,
    crest_elevation_m=crest,
    mode=FailureMode.PIPING,
)
hg = simulate(
    geometry=geom,
    storage=sc,
    crest_elevation_m=crest,
    initial_stage_m=crest,
    dt_s=10.0,
    duration_s=6 * 3600,
)

peak = hg.peak_outflow_m3s
print(f"Breach B_avg      : {geom.bottom_width_m:.1f} m")
print(f"Formation time    : {geom.formation_time_s/60:.1f} min")
print(f"Peak outflow      : {peak:,.0f} m^3/s at {hg.time_to_peak_s/60:.1f} min")

# ---- 3. Emit the [TIMESERIES] + [INFLOWS] blocks for the dam-toe node ----
inflow_block = format_inflows_block(
    hg,
    node_name="JN_Toe",
    timeseries_name="TS_TetonBreach",
    start_datetime=START,
    units="CMS",
    decimate=6,                 # dt_s=10 -> one row per minute
)

# ---- 4. Downstream routing network ---------------------------------------
# Channel sized to convey the breach peak without pathological surcharge:
# trapezoidal, 300 m base, 3H:1V sides, 40 m deep (~16,800 m^2 @ full).
# Toe at the reservoir invert (900 m), sloping ~0.001 to a free outfall.
junctions = """[JUNCTIONS]
;;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded
;;-------------- ---------- ---------- ---------- ---------- ----------
JN_Toe           900.0      40.0       0.0        0.0        0.0
JN_2             898.0      40.0       0.0        0.0        0.0
JN_3             896.0      40.0       0.0        0.0        0.0
"""

outfalls = """[OUTFALLS]
;;Name           Elevation  Type       Stage Data       Gated    Route To
;;-------------- ---------- ---------- ---------------- -------- ----------
OUT_1            894.0      FREE                        NO
"""

conduits = """[CONDUITS]
;;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow
;;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------
C1               JN_Toe           JN_2             2000       0.035      0          0          0          0
C2               JN_2             JN_3             2000       0.035      0          0          0          0
C3               JN_3             OUT_1            2000       0.035      0          0          0          0
"""

# Trapezoidal: Geom1=depth, Geom2=base width, Geom3/Geom4=side slopes (H per V)
xsections = """[XSECTIONS]
;;Link           Shape        Geom1      Geom2      Geom3      Geom4      Barrels
;;-------------- ------------ ---------- ---------- ---------- ---------- ----------
C1               TRAPEZOIDAL  40.0       300.0      3.0        3.0        1
C2               TRAPEZOIDAL  40.0       300.0      3.0        3.0        1
C3               TRAPEZOIDAL  40.0       300.0      3.0        3.0        1
"""

coordinates = """[COORDINATES]
;;Node           X-Coord            Y-Coord
;;-------------- ------------------ ------------------
JN_Toe           0.000              0.000
JN_2             2000.000           0.000
JN_3             4000.000           0.000
OUT_1            6000.000           0.000
"""

options = f"""[TITLE]
Teton-scale dam-breach routing example -- generated by swmm-breach.
Froehlich (2008) piping breach routed level-pool, applied as INFLOWS at the
dam toe (JN_Toe) and conveyed down a trapezoidal channel to a free outfall.
Peak breach outflow ~{peak:,.0f} m3/s. Units: CMS / meters.

[OPTIONS]
FLOW_UNITS           CMS
INFILTRATION         HORTON
FLOW_ROUTING         DYNWAVE
LINK_OFFSETS         DEPTH
MIN_SLOPE            0
ALLOW_PONDING        NO
SKIP_STEADY_STATE    NO

START_DATE           06/05/2026
START_TIME           14:00:00
REPORT_START_DATE    06/05/2026
REPORT_START_TIME    14:00:00
END_DATE             06/05/2026
END_TIME             20:00:00
SWEEP_START          01/01
SWEEP_END            12/31
DRY_DAYS             0
REPORT_STEP          00:01:00
WET_STEP             00:01:00
DRY_STEP             00:05:00
ROUTING_STEP         0:00:05
RULE_STEP            00:00:00

INERTIAL_DAMPING     PARTIAL
NORMAL_FLOW_LIMITED  BOTH
FORCE_MAIN_EQUATION  H-W
VARIABLE_STEP        0.75
LENGTHENING_STEP     0
MIN_SURFAREA         1.167
MAX_TRIALS           8
HEAD_TOLERANCE       0.0015
SYS_FLOW_TOL         5
LAT_FLOW_TOL         5

[EVAPORATION]
CONSTANT         0.0
DRY_ONLY         NO

[REPORT]
INPUT      NO
CONTROLS   NO
SUBCATCHMENTS ALL
NODES ALL
LINKS ALL
"""

report_map = """[MAP]
DIMENSIONS -500.000 -500.000 6500.000 500.000
Units      Meters
"""

doc = (
    options
    + "\n"
    + junctions
    + "\n"
    + outfalls
    + "\n"
    + conduits
    + "\n"
    + xsections
    + "\n"
    + inflow_block          # contains [TIMESERIES] then [INFLOWS]
    + "\n"
    + coordinates
    + "\n"
    + report_map
)

OUT_INP.write_text(doc, encoding="ascii")
print(f"\nWrote {OUT_INP}")
print(f"  ({len(doc.splitlines())} lines)")
